/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nwk.com.br.frame;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import nwk.com.br.dao.UsuarioDAO;
import nwk.com.br.documents.ControleTexto;
import nwk.com.br.model.Usuario;

/**
 *
 * @author Richard Matheus
 */
public class CadUsuario extends javax.swing.JInternalFrame {
    private JDesktopPane jDesktopPanePrincipal = new JDesktopPane();
    private SimpleDateFormat sdf1= new SimpleDateFormat("dd-MM-yyyy");
    
    private Usuario usuario = new Usuario();
    private UsuarioDAO usuariodao = new UsuarioDAO();
    
    
    /**
     * Creates new form CadCliente
     */
    public CadUsuario() {
        initComponents();
        setDocuments();
    }
    
    //Adiciona o Internal Frame Usuario ao desktopPane para o cadastro de um novo usuario
    public void addCadUsuarioNew(JDesktopPane frame){
        this.jDesktopPanePrincipal = frame;
        
        //Diz que esse usuario nao é para update e sim para insert
        this.usuario.setUpdate(false);
        
        //Esconde e desabilita o botao EXCLUIR
        jButtonExluir.setVisible(false);
        jButtonExluir.setEnabled(false);
        
        //Adiciona a data e o codigo no documento
        addData();
        addCod();
                
        //Adiciona o Internal Frame Usuario ao desktopPane
        frame.add(this);
        this.setVisible(true);
    }
    
    //Adiciona o Internal Frame Usuario ao desktopPane para a atualização de um usuario ja existente
    public void addCadUsuarioUpdate(JDesktopPane frame, Usuario user){
        this.usuario = user;
        
        
        //Pega os valor do usuario em questao e os adiciona aos seus respectivos campos
        jTextCod.setText(Integer.toString(user.getCod()));
        jTextNome.setText(user.getNome());
        jPassword.setText(user.getSenha());
        jTextDCadastro.setText(sdf1.format(user.getData()).toString());
        
        //Adiciona o Internal Frame Usuario ao desktopPane
        frame.add(this);
        this.setVisible(true);
    }
    
    //coloca a data atual no campo de data
    private void addData(){
        Date data = new Date();
        jTextDCadastro.setText(sdf1.format(data).toString());
    }
    
    //pega o ultimo codigo e soma 1 a ele, assim gerando o novo id a ser usado.
    private void addCod(){
        int cod;
        cod = usuariodao.getMaxCod();
        cod++;
        
        jTextCod.setText(Integer.toString(cod));
    }
    
    //Valida se os dados de clientes estao preenchidos.
    private boolean validaUsuario(Usuario usuario){
        boolean valido = false;
        
        //se os campos forem preenchidos, torna o formulario valido
        if((usuario.getNome() != null) && (usuario.getSenha() != null) && (!usuario.getNome().equals("")) && (!usuario.getSenha().equals(""))){
            valido = true;
            System.out.println("validado");
        }
        
        return valido;
    }
    
    //Seta os documents dos campos de texto.
    private void setDocuments(){
        jTextNome.setDocument(new ControleTexto(60));
        jPassword.setDocument(new ControleTexto(8));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextCod = new javax.swing.JTextField();
        jTextNome = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jTextDCadastro = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonExluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Usuario");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Usuario"));

        jLabel1.setText("Codigo :");

        jLabel2.setText("Nome :");

        jLabel3.setText("Senha :");

        jTextCod.setEditable(false);

        jLabel4.setText("Cadastrado :");

        jTextDCadastro.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextCod, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextDCadastro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextDCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonExluir.setText("Excluir");
        jButtonExluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonExluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonCancelar)
                        .addComponent(jButtonExluir)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        Usuario usuario = new Usuario();
        boolean valido = false;
        boolean inserido = false;
        
        usuario.setCod(Integer.parseInt(jTextCod.getText()));
        usuario.setNome(jTextNome.getText());
        usuario.setSenha(jPassword.getText());
        usuario.setData(jTextDCadastro.getText());
        
        
        valido = validaUsuario(usuario);
        
        if(valido == true){
            if(this.usuario.isUpdate() == false){
                
                //Recebe o retorno se o usuario foi inserido com sucesso ou nao
                inserido = usuariodao.inserir(usuario);
                if(inserido == true){
                    JOptionPane.showMessageDialog(null, "Usuario Inserido Com Sucesso");
                    dispose();
                } 
                
            }else if(this.usuario.isUpdate() == true){
                //Recebe o retorno se o usuario foi atualizado com sucesso ou nao
                inserido = usuariodao.atualizar(usuario);
                if(inserido == true){
                    JOptionPane.showMessageDialog(null, "Usuario Atualizado Com Sucesso");
                    dispose();
                } 
            }
            
        } else if(valido == false){
            JOptionPane.showMessageDialog(null, "Campos Não preenchidos, verifique!");
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        //Altera as mensagens da caixa de confirmação para Sim ou Não
        UIManager.put("OptionPane.yesButtonText", "Sim");  
        UIManager.put("OptionPane.noButtonText", "Não");
        
        //Mostra uma caixa de confirmação se o usuario deseja mesmo sair
        switch(JOptionPane.showConfirmDialog(null, "Deseja Mesmo Sair?", "Confirma" ,JOptionPane.YES_NO_OPTION)){
            case 0:
                setVisible(false);
                dispose();
                break;
            case 1:
                break;
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonExluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExluirActionPerformed
        //Altera as mensagens da caixa de confirmação para Sim ou Não
        UIManager.put("OptionPane.yesButtonText", "Sim");  
        UIManager.put("OptionPane.noButtonText", "Não");
        
        //Mostra uma caixa de confirmação se o usuario deseja mesmo sair
        switch(JOptionPane.showConfirmDialog(null, "Deseja Mesmo Exluir Esse Usuario?", "Confirma" ,JOptionPane.YES_NO_OPTION)){
            case 0:
                Usuario usuario = new Usuario();
                boolean valido = false;
                
                usuario.setCod(Integer.parseInt(jTextCod.getText()));
                valido = usuariodao.excluir(usuario);
                
                if(valido){
                    JOptionPane.showMessageDialog(null, "Usuario Excluido Com Sucesso!");
                    dispose();
                }
                break;
            case 1:
                break;
        }
    }//GEN-LAST:event_jButtonExluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextCod;
    private javax.swing.JTextField jTextDCadastro;
    private javax.swing.JTextField jTextNome;
    // End of variables declaration//GEN-END:variables
}
