/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nwk.com.br.frame;

import javax.swing.JDesktopPane;
import javax.swing.table.TableModel;
import nwk.com.br.structures.PlataformaStru;
import nwk.com.br.model.Plataforma;

/**
 *
 * @author Richard Matheus
 */
public class ConsultaPlataforma extends javax.swing.JInternalFrame {
    private PlataformaStru stru = new PlataformaStru();
    private JDesktopPane jDesktopPanePrincipal = new JDesktopPane();
    /**
     * Creates new form ConsultaPlataforma
     */
    public ConsultaPlataforma() {
        initComponents();
        atualizaTable();
    }
    
    //Carrega os dados na tabela
    private void atualizaTable(){
        TableModel model = (TableModel) (stru.getTable());
        jTablePlataforma.setModel(model);
        
        //Seta as dimensões das colunas
        jTablePlataforma.getColumnModel().getColumn(0).setMinWidth(35);
        jTablePlataforma.getColumnModel().getColumn(0).setMaxWidth(35);
        
        jTablePlataforma.getColumnModel().getColumn(2).setMinWidth(100);
        jTablePlataforma.getColumnModel().getColumn(2).setMaxWidth(100);
        //jTableClientes.getColumnModel().getColumn(1).setPreferredWidth(350);
    }
    
    //recebe a desktoppane do mainframe
    public void addConsultaPlataforma(JDesktopPane frame){
        
        this.jDesktopPanePrincipal = frame;
        jDesktopPanePrincipal.add(this);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlataforma = new javax.swing.JTable();
        jButtonInserir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta Plataforma");

        jTablePlataforma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePlataforma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePlataformaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePlataforma);

        jButtonInserir.setText("Inserir");
        jButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonInserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonInserir, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirActionPerformed
        // TODO add your handling code here:
        CadPlataforma cadPlataforma = new CadPlataforma();
        dispose();
        cadPlataforma.addCadPlataformaNew(jDesktopPanePrincipal);
    }//GEN-LAST:event_jButtonInserirActionPerformed

    private void jTablePlataformaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePlataformaMouseClicked
        Plataforma plataforma = new Plataforma();
        CadPlataforma cadPlataforma = new CadPlataforma();
        
        int linhaSelecionada = jTablePlataforma.getSelectedRow();
        
        plataforma.setCod(Integer.parseInt(jTablePlataforma.getValueAt(linhaSelecionada, 0).toString()));
        plataforma.setNome(jTablePlataforma.getValueAt(linhaSelecionada, 1).toString());
        plataforma.setData(jTablePlataforma.getValueAt(linhaSelecionada, 2).toString());
        plataforma.setUpdate(true);
        
        dispose();
        cadPlataforma.addCadPlataformaUpdate(jDesktopPanePrincipal, plataforma);
    }//GEN-LAST:event_jTablePlataformaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInserir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePlataforma;
    // End of variables declaration//GEN-END:variables
}
